### ISSUE TITLE
How does this work?

### ISSUE THREAD

**Issue by Kees030** [CHEF-KOCH/regtweaks#1]
I found your link on MDL\Big Collection Of Windows 7 Reg Tweaks, however I've no clue what to do now. How do I download the manual and tweaks?

I've joined several RegTweaks into 1 .reg-file and made a .bat to install them silently. It's probably a noob-way to do it, yet it works in Win7Pro. When updating to Win10Pro the tweaks are lost. I've tried to upload them in .zip, however the system doesn't accept it.

Can you please guide me?

**Comment by CHEF-KOCH** [comment]
Hello and thanks for your interest.

Currently it's on my ToDo (see [Readme](https://github.com/CHEF-KOCH/regtweaks/blob/master/README.md)) to realse an GUI or something like an script/tweak parser which gives you an description and or options to do backups. Maybe something like [RSW](http://www.winfaq.de/download_rsw.htm).

Currently you can download everything via GIT or manually one-by-one via the 'Raw' buttons.

**Comment by Kees030** [comment]
Thank you for your response. Unfortunately I still don't understand what to
do. Downloading all seems to force me to use a GIT Desktop I don't want???

I donloaded the .zip, however there are not 600+ tweaks 😕


2015-12-10 2:14 GMT+01:00 CHEF-KOCH <notifications@github.com>:

**Comment by CHEF-KOCH** [comment]
What do exactly want, so that I can help you.

**Comment by Kees030** [comment]
Thank you for your help :)

I'd like to do a silent install of several RegTweaks with 1 mouseclick (the
same on several PC's, whenever I reinstall them). I wanted to chain the
individual tweaks, however I couldn't figure out how to. So I copied them
into one .reg-file and made a .bat-file to instal silently. Since gmail
doesn't allow sending .bat I've uploaded the .reg and .bat files in a .zip:
https://dl.dropboxusercontent.com/u/65438146/RegTweaks.zip

 I'd like to add more tweaks in a more sophisticated way ;)

Kind Regards, Kees



2015-12-11 5:14 GMT+01:00 CHEF-KOCH <notifications@github.com>:

**Comment by Kees030** [comment]
bump

**Comment by Kees030** [comment]
Is this still alive?

**Comment by CHEF-KOCH** [comment]
Yes it is.

**Comment by rubo77** [comment]
So please add instructions to the Readme, how to use this  exactly as a noob 😃

**Comment by Kees030** [comment]
I still didn't figure out how find, download and apply the tweaks. So, comment from rubo77 +1.

**Comment by Atavic** [comment]
On the [repo](https://github.com/CHEF-KOCH/regtweaks) click on the green button _Clone or download_ then _Zip download_.

Let's say you're on Win 10, you open the zip file locally and go to _Cortana_ folder, then double click on _Kill Cortana.reg_

That kills Cortana service.

**Comment by Kees030** [comment]
Hello,

I can't view 'regtweaks' on GitHub anymore; getting 404. Where is it?

Best Regards,
Kees

2015-12-11 19:27 GMT+01:00 Kees van Rijsbergen <kees030@gmail.com>:

**Comment by rubo77** [comment]
Why did you close this?

It would be really helpful, if you add the information from this issue to the README on the startpage

**Comment by CHEF-KOCH** [comment]
It's already mentioned since the beginning of this project under project goal + I keep people updated with a list what is already done, which shows the GUI is done but it needs more testing before I finally can roll it out.
