### ISSUE TITLE
dxtool?

### ISSUE THREAD

**Issue by L-a-n-g-o-l-i-e-r-s** [CHEF-KOCH/regtweaks#12]
What is it? How is it used? There's no documentation with your commit or the tool.

I tried searching it, but a lot of the results were unrelated, the ones related were in another language and the translations didn't make much sense.

Thanks

**Comment by CHEF-KOCH** [comment]
DXTool is a small util which provides:
* Reg2Inf
* Grant Admin Full Control via subinacl/SetAcl
* GOscdimg 
* GUPX
* CabTool 
* Registry Export
* SFX Tool

The developer if [OnePrice](https://www.wincert.net/forum/index.php?/profile/5798-onepiece/). I added it for test reasons and I will merge it's function into the final program.

**Comment by L-a-n-g-o-l-i-e-r-s** [comment]
So it must be more efficient than some of the tools it's replacing then such as subinacl/setacl

looking forward to context menu options with this, thanks
