### ISSUE TITLE
Disable SSL 2.0.reg spell error

### ISSUE THREAD

**Issue by slpcat** [CHEF-KOCH/regtweaks#13]
[HKEY_LOCAL_MACHINE\SYSTEM\CurrentControlSet\Control\SecurityProviders\SCHANNEL\Protocols\SL 2.0\Server]

should be  “SSL 2.0”

**Comment by kronflux** [comment]
@slpcat is correct.
[This line](https://github.com/CHEF-KOCH/regtweaks/blob/master/OS%20independent/Security/SSL/2.0/Disable%20SSL%202.0.reg#L3) should be `[HKEY_LOCAL_MACHINE\SYSTEM\CurrentControlSet\Control\SecurityProviders\SCHANNEL\Protocols\SSL 2.0\Server]`
