### ISSUE TITLE
Reverse win10shitremober.bat?!

### ISSUE THREAD

**Issue by seiterseiter** [CHEF-KOCH/regtweaks#2]
Hello is there a way to reverse the effects that win10shitremover.bat does?

**Comment by mikhoul** [comment]
Maybe with this file: https://github.com/CHEF-KOCH/regtweaks/blob/master/Win%2010%2Freset_defaults_beta.txt  but I'm not really sure.

**Comment by seiterseiter** [comment]
It didnt do it..

**Comment by CHEF-KOCH** [comment]
Do you need to reverse every settings or only a specific one?

**Comment by seiterseiter** [comment]
Im not sure which one does it but when using that bat file (it could be another of yours) but it causes the "Hidden items" but in in explorer view panel and in the options thing to auto uncheck it self. Even editing the registry doesnt fix it.

Any help would be great

**Comment by CHEF-KOCH** [comment]
Thanks I will look at it, but just to ensure, which Windows version do you use TH1 or TH2 build?

**Comment by seiterseiter** [comment]
How would I tell? Im on Windows 10 but dont know what TH1 or TH2 means.

**Comment by CHEF-KOCH** [comment]
Start + R -> type winver if it's shows Build 10240 it's TH a higher number is TH 2. TH1 and Th 2 are the [branch names](http://www.winbeta.org/news/upcoming-windows-10-insider-build-will-be-rtm-development-branch-th1). But doesn't matter now, I looked myself and the settings are still the same in TH2. 

But I found out that you're correct with the state that win10shitremover.bat changes the Windows Explorer default view. It's mentioned (but not fully documented at [line 58](https://github.com/CHEF-KOCH/regtweaks/blob/master/OS%20independent/Batch/w10/win10shitremover.bat#L58). 

https://raw.githubusercontent.com/CHEF-KOCH/regtweaks/master/OS%20independent/test/reverse%20for%20issue%20%232.reg

**Comment by seiterseiter** [comment]
Thank you! It works perfectly now :)

**Comment by seiterseiter** [comment]
Okay I rebooted my PC and its happening again.. Expect when I try to run that .reg file you posted it shows this http://i.imgur.com/JJHPOkg.png

**Comment by CHEF-KOCH** [comment]
Can you manually edit the entries? start button + r, type: regedit, and then navigate to the keys, after changing reboot the system once again. 

If not then the changes are not done by my registry tweak because it seems you don't have access to it (and in this case the .bat shows failed [only for 0.1 second but it's there]) and it will be automatically skipped.

**Comment by seiterseiter** [comment]
It gives me a similar error about permissions. Im on an admin account because im on the only account on this pc haha.

**Comment by seiterseiter** [comment]
Could it be my antivirus doing it? (Bitdefender)

**Comment by CHEF-KOCH** [comment]
Sorry I don't know, just try to disable it and try to import or manually edit it. But normally the explorer changes aren't special protected since you can access this (any user) via GUI.

**Comment by mikhoul** [comment]
@seiterseiter  if somebody/something have messed with your <ins>registry permissions</ins> you can try the free version of this software to reset it: http://www.tweaking.com/content/page/windows_repair_all_in_one.html
