### ISSUE TITLE
Games Bordeless REG

### ISSUE THREAD

**Issue by MarshallTaylorV** [CHEF-KOCH/regtweaks#27]
Hello I love your work helped me a lot on Windows I could know if there is a reg file which makes all my games without border and that it is always at the top thanks again for your work

**Comment by CHEF-KOCH** [comment]
Not via registry only but [borderless-gaming](https://github.com/Codeusa/Borderless-Gaming/releases) is what you're looking for,

**Comment by vasudev-gm** [comment]
> Not via registry only but [borderless-gaming](https://github.com/Codeusa/Borderless-Gaming/releases) is what you're looking for,

Was going to suggest Borderless gaming app but Chef Koch beat me to it!
Make sure Xbox game overlay or RTSS overlay aren't running because sometimes Win key+Tab might make the game crash. I solved it by disabling RTSS overlay.
