### ISSUE TITLE
Questions about Office Telemetry and Win10 Aero Tweaks

### ISSUE THREAD

**Issue by Bamajon1974** [CHEF-KOCH/regtweaks#32]
(Please let me know if there is a separate place to ask questions)

1. Is there an explanation what the Office 16 Telemetry tweaks turn on or off? Are they valid for Microsoft/Office 365 suite?
https://github.com/CHEF-KOCH/regtweaks/tree/master/OS%20independent/Ms%20Office/Disabel%20office%2016%20telemetry

2. Enable Aero With Blur -- does this tweak need AeroGlass to work? 
Enable Aero with Blur.reg

Thanks!

**Comment by CHEF-KOCH** [comment]
1. Disabled telemetry (as the name says).
2. You need AeroGlass, that#s correct since there is no "Areo theme" (which supports a glassy look) in Windows 10.

**Comment by Bamajon1974** [comment]
Is this office telemetry disabling reg file applicable to Office 365 products or older, standalone versions?

**Comment by CHEF-KOCH** [comment]
It works in 365 too but some toggles getting ignored because they simply do not exist.

**Comment by Bamajon1974** [comment]
Took me a while but I found some explanation for the tweaks. Please refer to the link below. About halfway down are group policy/registry editor settings for the telemetry tweaks. It seems that since Office 365 is cloud based, disabling all of the telemetry may cause the suite to not function properly so the tweaks should be applied carefully. 

https://getadmx.com/?Category=Office2016&Policy=office16.Office.Microsoft.Policies.Windows::L_Screenshot
