### ISSUE TITLE
Need registry tweak to disable "Use automatic configuration script"

### ISSUE THREAD

**Issue by vavavr00m** [CHEF-KOCH/regtweaks#4]
How do I enable LAN config?

![lan admin](https://cloud.githubusercontent.com/assets/4675132/15147543/ccfcbb88-16f3-11e6-98e8-a15fc283befa.png)

![lan](https://cloud.githubusercontent.com/assets/4675132/15147555/d8831cd6-16f3-11e6-9c55-f9e27f5fb9e0.png)

**Comment by CHEF-KOCH** [comment]
<code>HKEY_CURRENT_USER\Software\Microsoft\Windows\CurrentVersion\Internet Settings</code>

```bash
"AutoDetect "=dword:00000000
"MigrateProxy"=dword:00000001
"ProxyEnable"=dword:00000001
"ProxyHttp1.1"=dword:00000000
"ProxyServer"="http://ProxyServername:80"
"ProxyOverride"="<local>"
````

If you unsure you can delete everything under Internet Settings, after a system restart + Browser restart (twice - one for reset and one for getting the defaults) should work.

**Comment by vavavr00m** [comment]
I deleted everything under Internet Settings and rebooted twice and nothing happened (LAN settings is still grayed and Use automatic configuration script is still checked),  just this appeared:
EnableNegotiate dword:00000001

**Comment by CHEF-KOCH** [comment]
Strange, which OS you use? 7?

**Comment by vavavr00m** [comment]
Windows 7 Ultimate x64

**Comment by CHEF-KOCH** [comment]
Please try in IE <code>Tools > Internet Options > Advanced tab > Reset</code> and see if that helps after a restart.

**Comment by vavavr00m** [comment]
Does not work. Btw, it's in Chrome proxy settings, if it would make any difference.

**Comment by CHEF-KOCH** [comment]
Seems you destroyed your [security zone](https://social.technet.microsoft.com/Forums/windowsserver/en-US/cd9e1fc2-e209-49f4-ae4a-78222969c6b2/some-settings-are-managed-by-your-system-administrator?forum=winserversecurity).

**Comment by CHEF-KOCH** [comment]
Is this now solved ?

**Comment by vavavr00m** [comment]
A. Aready "not configured"
1.    Click Start, type gpedit.msc and press Enter.
2.    Locate to Computer Configuration -> Administrative Templates -> Windows Components -> Internet Explorer.
3.    Double-click “Security Zones: Do not allow users to change policies” on the right pane
4.    Choose “Not Configured” and click OK.
5.    Restart the computer and test the result.

B. Deleted/non-existent, no effect.
You can also delete the registry key “Security_HKLM_only” under HKEY_LOCAL_MACHINE\Software\Policies\Microsoft\Windows\CurrentVersion\Internet
Settings
HKEY_CURRENT_USER\Software\Policies\Microsoft\Internet Explorer\Control Panel

C. Added, no effect
[HKEY_LOCAL_MACHINE\SOFTWARE\Policies\Microsoft\Windows\CurrentVersion\Internet Settings]
"ProxySettingsPerUser"=dword:00000001

How to proceed? I tried a few things there but nothing worked for me. I can't even install AVG nor copy SpyBot on the machine.

**Comment by CHEF-KOCH** [comment]
I will look into this give me some time.

**Comment by CHEF-KOCH** [comment]
Sr, I need to give up on this, it's impossible to reproduce for me, I tried manually to delete the "Internet Settings" restarted and Windows got the SecurityZone automatically back. I also tried Other mentioned workarounds and it worked. I must admit it was not under a fully latest patched Win 7 since I used the original MS image in a VM to test it. 

Please give me the .reg file you imported and I will delete this since it seems it no longer works as it should.

I suggest to fix your problem that you re-create a new user account.

Sorry for the unpleasantness. I will try to complete the GUI this year and add an automatically roll-back action to it in case MS (again) changed something.

**Comment by vavavr00m** [comment]
I only deleted without importing any keys because I was uncertain what to do. BTW, the issue was resolved by scanning the server with MBAM. The following registry keys were affected and quarantined:
HKLM\SOFTWARE\MICROSOFT\WINDOWS\CURRENTVERSION\INTERNET SETTINGS 
"AutoConfigURL"

HKLM\SOFTWARE\WOW6432NODE\MICROSOFT\WINDOWS\CURRENTVERSION\INTERNET SETTINGS
"AutoConfigURL"

HKLM\SYSTEM\CONTROLSET001\SERVICES\NLASVC\PARAMETERS\INTERNET\MANUALPROXIES

I will scan the other infected machine with MBAM and send you the registry keys if you need it.

**Comment by CHEF-KOCH** [comment]
Okay, that's fine, thx.
