### ISSUE TITLE
How to disable Notification windows security?

### ISSUE THREAD

**Issue by ttn10** [CHEF-KOCH/regtweaks#6]
Hi, how to remove this Notification?
http://i.imgur.com/aImMWaJ.png
Thanks :+1:

**Comment by CHEF-KOCH** [comment]
´´´bash
Windows Registry Editor Version 5.00

[HKEY_CURRENT_USER\Software\Microsoft\Windows\CurrentVersion\Explorer\Advanced]
“EnableBalloonTips”=dword:00000000
```
