### ISSUE TITLE
Blacklisted by defender

### ISSUE THREAD

**Issue by katlogic** [CHEF-KOCH/regtweaks#7]
https://i.imgur.com/BcNNPBd.png

```
Category: Trojan

Description: This program is dangerous and executes commands from an attacker.

Recommended action: Remove this software immediately.

Items: 
containerfile:C:\Users\kat\Downloads\regtweaks-master.zip
file:C:\Users\kat\Downloads\regtweaks-master.zip->regtweaks-master/Win 10/Theme/AeroGlass10240.rar->AeroGlass10240\AeroGlass\AeroGlass_x86.exe
webfile:C:\Users\kat\Downloads\regtweaks-master.zip|https://codeload.github.com/CHEF-KOCH/regtweaks/zip/master|browser_broker.exe
```

Most likely a false alarm. Still, annoying when one wants to download regtweaks on new machine to de-crap it. Maybe move the EXEs to a branch separate from master?

**Comment by CHEF-KOCH** [comment]
It's legit [process memoy patch](https://www.virustotal.com/de/file/9ab89afe2797f80094d342930f7081ebe236fedb8ac8faeec6f9e331e1786476/analysis/1467716308/) method.
